# Generated by Django 4.0.4 on 2022-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_beat', models.IntegerField(max_length=3)),
                ('blood_pressure', models.IntegerField(max_length=3)),
                ('body_temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('oxygen_saturation', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
